[2023-07-28 16:07:10,138] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: dag_test.get_data_postgres manual__2023-07-28T16:07:09.354701+00:00 [queued]>
[2023-07-28 16:07:10,149] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: dag_test.get_data_postgres manual__2023-07-28T16:07:09.354701+00:00 [queued]>
[2023-07-28 16:07:10,150] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2023-07-28 16:07:10,150] {taskinstance.py:1357} INFO - Starting attempt 1 of 1
[2023-07-28 16:07:10,150] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2023-07-28 16:07:10,167] {taskinstance.py:1377} INFO - Executing <Task(PythonOperator): get_data_postgres> on 2023-07-28 16:07:09.354701+00:00
[2023-07-28 16:07:10,172] {standard_task_runner.py:52} INFO - Started process 2609 to run task
[2023-07-28 16:07:10,175] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'dag_test', 'get_data_postgres', 'manual__2023-07-28T16:07:09.354701+00:00', '--job-id', '294', '--raw', '--subdir', 'DAGS_FOLDER/simple_dag_connection.py', '--cfg-path', '/tmp/tmp0st3ojsx', '--error-file', '/tmp/tmpllnzr1cs']
[2023-07-28 16:07:10,176] {standard_task_runner.py:80} INFO - Job 294: Subtask get_data_postgres
[2023-07-28 16:07:10,230] {task_command.py:369} INFO - Running <TaskInstance: dag_test.get_data_postgres manual__2023-07-28T16:07:09.354701+00:00 [running]> on host ebe3e165ffca
[2023-07-28 16:07:10,317] {taskinstance.py:1571} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=dag_test
AIRFLOW_CTX_TASK_ID=get_data_postgres
AIRFLOW_CTX_EXECUTION_DATE=2023-07-28T16:07:09.354701+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2023-07-28T16:07:09.354701+00:00
[2023-07-28 16:07:10,331] {logging_mixin.py:115} INFO - connect engine Postgresql
[2023-07-28 16:07:10,331] {python.py:173} INFO - Done. Returned value was: Engine(postgresql://postgres:***@172.17.0.1:5432/dwh_final)
[2023-07-28 16:07:10,338] {xcom.py:585} ERROR - Could not serialize the XCom value into JSON. If you are using pickle instead of JSON for XCom, then you need to enable pickle support for XCom in your *** config.
[2023-07-28 16:07:10,339] {taskinstance.py:1889} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/session.py", line 68, in wrapper
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 2380, in xcom_push
    session=session,
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/session.py", line 68, in wrapper
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/xcom.py", line 197, in set
    map_index=map_index,
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/xcom.py", line 582, in serialize_value
    return json.dumps(value).encode('UTF-8')
  File "/usr/local/lib/python3.7/json/__init__.py", line 231, in dumps
    return _default_encoder.encode(obj)
  File "/usr/local/lib/python3.7/json/encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/usr/local/lib/python3.7/json/encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "/usr/local/lib/python3.7/json/encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type Engine is not JSON serializable
[2023-07-28 16:07:10,349] {taskinstance.py:1400} INFO - Marking task as FAILED. dag_id=dag_test, task_id=get_data_postgres, execution_date=20230728T160709, start_date=20230728T160710, end_date=20230728T160710
[2023-07-28 16:07:10,360] {standard_task_runner.py:97} ERROR - Failed to execute job 294 for task get_data_postgres (Object of type Engine is not JSON serializable; 2609)
[2023-07-28 16:07:10,387] {local_task_job.py:156} INFO - Task exited with return code 1
[2023-07-28 16:07:10,470] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
